# Generated by Django 5.0 on 2025-11-01 17:53

import apps.common.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms_builder', '0001_initial'),
        ('kpi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month of submission')),
                ('year', models.IntegerField(help_text='Year of submission')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('NEEDS_REVISION', 'Needs Revision'), ('HOD_APPROVED', 'HoD Approved'), ('DEAN_APPROVED', 'Dean Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Current status of the submission', max_length=20)),
                ('awarded_points', models.DecimalField(decimal_places=2, default=0, help_text='Points awarded by reviewer', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('review_comment', models.TextField(blank=True, help_text='Comment from reviewer')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the submission was reviewed', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the submission was submitted (status changed from DRAFT)', null=True)),
                ('dean_approved', models.BooleanField(default=False, help_text='Whether Dean has given final approval')),
                ('dean_approved_at', models.DateTimeField(blank=True, help_text='When Dean approved', null=True)),
                ('dean_approver', models.ForeignKey(blank=True, help_text='Dean who gave final approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_approved_submissions', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, help_text='User who reviewed/approved this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('sub_parameter', models.ForeignKey(help_text='Sub-parameter this submission is for', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='kpi.subparameter')),
                ('user', models.ForeignKey(help_text='User who created this submission', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'db_table': 'submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='Uploaded file', upload_to=apps.common.utils.get_upload_path)),
                ('original_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('field', models.ForeignKey(blank=True, help_text='Dynamic field this attachment is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='forms_builder.dynamicfield')),
                ('submission', models.ForeignKey(help_text='Submission this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'db_table': 'attachments',
                'ordering': ['submission', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(help_text='Field name (cached for performance)', max_length=100)),
                ('value', models.TextField(blank=True, help_text='Field value (JSON for complex types)')),
                ('field', models.ForeignKey(help_text='Dynamic field this value is for', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='forms_builder.dynamicfield')),
                ('submission', models.ForeignKey(help_text='Submission this value belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'Submission Field Value',
                'verbose_name_plural': 'Submission Field Values',
                'db_table': 'submission_field_values',
                'ordering': ['submission', 'field__order'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', '-created_at'], name='submissions_user_id_1dd2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['sub_parameter', 'month', 'year'], name='submissions_sub_par_92caa6_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='submissions_status_dcc854_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['month', 'year'], name='submissions_month_af0f62_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['-created_at'], name='submissions_created_80fb8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('user', 'sub_parameter', 'month', 'year')},
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['submission'], name='attachments_submiss_3f8b98_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['-created_at'], name='attachments_created_b18582_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionfieldvalue',
            index=models.Index(fields=['submission'], name='submission__submiss_784e52_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionfieldvalue',
            index=models.Index(fields=['field'], name='submission__field_i_2c325d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionfieldvalue',
            unique_together={('submission', 'field')},
        ),
    ]
