# Generated by Django 5.0 on 2025-11-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Department code (e.g., CSE, ECE, MECH)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Department name (e.g., Computer Science Engineering)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Department description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the department is active')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='departments_code_9f933a_idx'), models.Index(fields=['is_active'], name='departments_is_acti_a777bd_idx')],
            },
        ),
    ]
