# Generated by Django 5.0 on 2025-11-01 17:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutoffWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month for this cutoff window')),
                ('year', models.IntegerField(help_text='Year for this cutoff window')),
                ('faculty_submit_deadline', models.DateTimeField(help_text='Deadline for faculty to submit')),
                ('hod_approve_deadline', models.DateTimeField(help_text='Deadline for HoD to approve')),
                ('dean_approve_deadline', models.DateTimeField(help_text='Deadline for Dean to give final approval')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this cutoff window is active')),
                ('departments', models.ManyToManyField(blank=True, help_text='Departments this window applies to (blank = all departments)', related_name='cutoff_windows', to='departments.department')),
            ],
            options={
                'verbose_name': 'Cutoff Window',
                'verbose_name_plural': 'Cutoff Windows',
                'db_table': 'cutoff_windows',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='MainParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the main parameter', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the main parameter')),
                ('weightage', models.DecimalField(decimal_places=2, default=1.0, help_text='Weightage or percentage for this parameter', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('role_owner', models.CharField(choices=[('FACULTY', 'Faculty'), ('HOD', 'Head of Department')], default='FACULTY', help_text='Who owns this parameter (Faculty or HoD)', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this parameter is active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Main Parameter',
                'verbose_name_plural': 'Main Parameters',
                'db_table': 'main_parameters',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='main_parame_is_acti_1f6ac3_idx'), models.Index(fields=['role_owner'], name='main_parame_role_ow_d6f755_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the sub-parameter', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the sub-parameter')),
                ('max_points', models.PositiveIntegerField(help_text='Maximum effort coins/points for this sub-parameter')),
                ('approval_routing', models.CharField(choices=[('HOD', 'HoD Approval'), ('OTHER', 'Other Approver')], default='HOD', help_text='Routing for approval (HoD or Other)', max_length=20)),
                ('other_approver_email', models.EmailField(blank=True, help_text='Email of other approver (if routing is OTHER)', max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this sub-parameter is active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('main_parameter', models.ForeignKey(help_text='Parent main parameter', on_delete=django.db.models.deletion.CASCADE, related_name='sub_parameters', to='kpi.mainparameter')),
            ],
            options={
                'verbose_name': 'Sub Parameter',
                'verbose_name_plural': 'Sub Parameters',
                'db_table': 'sub_parameters',
                'ordering': ['main_parameter', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HodSubParamMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aggregation', models.CharField(choices=[('AVERAGE', 'Average')], default='AVERAGE', help_text='Aggregation type', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mapping is active')),
                ('faculty_subparam', models.ForeignKey(help_text='Corresponding Faculty sub-parameter', limit_choices_to={'main_parameter__role_owner': 'FACULTY'}, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_mappings', to='kpi.subparameter')),
                ('hod_subparam', models.ForeignKey(help_text='HoD sub-parameter', limit_choices_to={'main_parameter__role_owner': 'HOD'}, on_delete=django.db.models.deletion.CASCADE, related_name='hod_mappings', to='kpi.subparameter')),
            ],
            options={
                'verbose_name': 'HOD Sub-Parameter Mapping',
                'verbose_name_plural': 'HOD Sub-Parameter Mappings',
                'db_table': 'hod_subparam_mappings',
                'ordering': ['hod_subparam'],
            },
        ),
        migrations.CreateModel(
            name='SubParameterWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this sub-parameter is enabled for this window')),
                ('cutoff_window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subparam_associations', to='kpi.cutoffwindow')),
                ('sub_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window_associations', to='kpi.subparameter')),
            ],
            options={
                'verbose_name': 'Sub-Parameter Window',
                'verbose_name_plural': 'Sub-Parameter Windows',
                'db_table': 'subparameter_windows',
            },
        ),
        migrations.AddIndex(
            model_name='cutoffwindow',
            index=models.Index(fields=['month', 'year', 'is_active'], name='cutoff_wind_month_d68609_idx'),
        ),
        migrations.AddIndex(
            model_name='cutoffwindow',
            index=models.Index(fields=['-year', '-month'], name='cutoff_wind_year_b35775_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cutoffwindow',
            unique_together={('month', 'year')},
        ),
        migrations.AddIndex(
            model_name='subparameter',
            index=models.Index(fields=['main_parameter', 'is_active'], name='sub_paramet_main_pa_25d5ff_idx'),
        ),
        migrations.AddIndex(
            model_name='subparameter',
            index=models.Index(fields=['approval_routing'], name='sub_paramet_approva_2b9abe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subparameter',
            unique_together={('main_parameter', 'name')},
        ),
        migrations.AddIndex(
            model_name='hodsubparammapping',
            index=models.Index(fields=['hod_subparam', 'is_active'], name='hod_subpara_hod_sub_9e11f3_idx'),
        ),
        migrations.AddIndex(
            model_name='hodsubparammapping',
            index=models.Index(fields=['faculty_subparam'], name='hod_subpara_faculty_b5b7be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hodsubparammapping',
            unique_together={('hod_subparam', 'faculty_subparam')},
        ),
        migrations.AlterUniqueTogether(
            name='subparameterwindow',
            unique_together={('sub_parameter', 'cutoff_window')},
        ),
    ]
