# Generated by Django 5.0 on 2025-11-01 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_REVISION', 'Needs Revision'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted')], help_text='Type of action performed', max_length=50)),
                ('target_model', models.CharField(help_text='Model name of the target object', max_length=100)),
                ('target_id', models.PositiveIntegerField(help_text='ID of the target object')),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('comment', models.TextField(blank=True, help_text='Additional comments or notes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the actor', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_lo_created_d8c226_idx'), models.Index(fields=['actor', '-created_at'], name='activity_lo_actor_i_929704_idx'), models.Index(fields=['target_model', 'target_id'], name='activity_lo_target__23e139_idx')],
            },
        ),
    ]
