# Generated by Django 5.0 on 2025-11-01 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this form template is active')),
                ('instructions', models.TextField(blank=True, help_text='Instructions for filling the form')),
                ('sub_parameter', models.OneToOneField(help_text='Sub-parameter this form is for', on_delete=django.db.models.deletion.CASCADE, related_name='form_template', to='kpi.subparameter')),
            ],
            options={
                'verbose_name': 'Dynamic Form Template',
                'verbose_name_plural': 'Dynamic Form Templates',
                'db_table': 'dynamic_form_templates',
                'ordering': ['sub_parameter'],
            },
        ),
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Machine name/key for this field (e.g., 'publication_title')", max_length=100)),
                ('label', models.CharField(help_text='Display label for this field', max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('percentage', 'Percentage'), ('date', 'Date'), ('url', 'URL'), ('select', 'Select'), ('multiselect', 'Multi Select'), ('file', 'File Upload'), ('multifile', 'Multiple Files')], help_text='Type of field', max_length=20)),
                ('help_text', models.TextField(blank=True, help_text='Help text to display under the field')),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder text for input fields', max_length=255)),
                ('is_required', models.BooleanField(default=False, help_text='Whether this field is required')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the form')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this field is active')),
                ('choices', models.JSONField(blank=True, default=list, help_text='Choices for select/multiselect fields (JSON array)')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum value for number/percentage fields', max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum value for number/percentage fields', max_digits=10, null=True)),
                ('pattern', models.CharField(blank=True, help_text='Regex pattern for validation', max_length=255)),
                ('max_length', models.PositiveIntegerField(blank=True, help_text='Maximum length for text fields', null=True)),
                ('max_files', models.PositiveIntegerField(default=1, help_text='Maximum number of files for file upload fields')),
                ('template', models.ForeignKey(help_text='Form template this field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms_builder.dynamicformtemplate')),
            ],
            options={
                'verbose_name': 'Dynamic Field',
                'verbose_name_plural': 'Dynamic Fields',
                'db_table': 'dynamic_fields',
                'ordering': ['template', 'order'],
                'indexes': [models.Index(fields=['template', 'order'], name='dynamic_fie_templat_a10801_idx'), models.Index(fields=['is_active'], name='dynamic_fie_is_acti_930d9a_idx')],
                'unique_together': {('template', 'name')},
            },
        ),
    ]
