# Generated by Django 5.0 on 2025-11-01 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeanApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField(help_text='Month of approval')),
                ('year', models.IntegerField(help_text='Year of approval')),
                ('total_points', models.DecimalField(decimal_places=2, default=0, help_text='Total points for this faculty for this window', max_digits=10)),
                ('comment', models.TextField(blank=True, help_text="Dean's comment")),
                ('is_approved', models.BooleanField(default=True, help_text='Whether approved or rejected')),
                ('dean', models.ForeignKey(help_text='Dean who approved', limit_choices_to={'role': 'DEAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='dean_approvals_given', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(help_text='Faculty being approved', limit_choices_to={'role': 'FACULTY'}, on_delete=django.db.models.deletion.CASCADE, related_name='dean_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dean Approval',
                'verbose_name_plural': 'Dean Approvals',
                'db_table': 'dean_approvals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['faculty', 'month', 'year'], name='dean_approv_faculty_19d855_idx'), models.Index(fields=['dean', '-created_at'], name='dean_approv_dean_id_c7e6f0_idx'), models.Index(fields=['-created_at'], name='dean_approv_created_174bb1_idx')],
                'unique_together': {('faculty', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(help_text='Action taken (APPROVED, REJECTED, NEEDS_REVISION)', max_length=50)),
                ('awarded_points', models.DecimalField(decimal_places=2, default=0, help_text='Points awarded (if approved)', max_digits=10)),
                ('comment', models.TextField(blank=True, help_text="Reviewer's comment")),
                ('previous_status', models.CharField(help_text='Status before this review', max_length=20)),
                ('new_status', models.CharField(help_text='Status after this review', max_length=20)),
                ('reviewer', models.ForeignKey(help_text='User who performed the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(help_text='Submission being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['submission', '-created_at'], name='reviews_submiss_ca79d2_idx'), models.Index(fields=['reviewer', '-created_at'], name='reviews_reviewe_ae7fe9_idx'), models.Index(fields=['-created_at'], name='reviews_created_6c5dce_idx')],
            },
        ),
    ]
